# Generated by Django 4.1 on 2022-09-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favourite_genre',
        ),
        migrations.AddField(
            model_name='profile',
            name='favourite_genre',
            field=models.ManyToManyField(help_text='Select your favourite genres', to='catalog.genre'),
        ),
    ]
