# Generated by Django 4.1 on 2022-09-16 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0010_remove_profile_favourite_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favourite_genre',
        ),
        migrations.CreateModel(
            name='Recommended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourite_genre', models.ManyToManyField(help_text='Select your favourite genres', to='catalog.genre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
