# Generated by Django 4.1 on 2022-09-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_remove_profile_favourite_genre_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favourite_genre',
            field=models.ManyToManyField(help_text='Select your favourite genres', to='catalog.genre'),
        ),
        migrations.DeleteModel(
            name='Recommended',
        ),
    ]
