# Generated by Django 4.1 on 2022-09-23 06:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_profile_favourite_genre_delete_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now, help_text='Enter day book was added'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile_images'),
        ),
    ]
