# Generated by Django 4.1 on 2022-09-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_book_date_added_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='book-default.jpg', upload_to='profile_images'),
        ),
    ]
