# Generated by Django 4.1 on 2022-09-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, help_text="Enter the author's biography", max_length=1000, null=True),
        ),
    ]
