# Generated by Django 4.1 on 2022-09-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_author_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nationality',
            field=models.CharField(default='Nigerian', help_text='Enter your nationality', max_length=100),
            preserve_default=False,
        ),
    ]
