# Generated by Django 4.1 on 2022-10-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_alter_profile_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_added',
            field=models.DateField(help_text='Enter day book was added: YYYY-MM-DD'),
        ),
    ]
